# Generated By: Claude Code (Claude Opus 5)
FROM python:3.14-slim

# Links the GHCR package to its source repo (required for GHCR publishing).
LABEL org.opencontainers.image.source="https://github.com/jewzaam/weather-exporter"

WORKDIR /app

# Install the package first (better layer caching). git is only needed to resolve
# the metrics-utility VCS requirement; purge it in the same layer so it does not
# ship in the image.
COPY pyproject.toml README.md LICENSE ./
COPY weather_exporter ./weather_exporter
RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && pip install --no-cache-dir . \
    && apt-get purge -y git && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

# Run as a non-root user
RUN useradd --create-home --uid 10001 appuser && chown -R appuser /app
USER appuser

# 8011 = prometheus metrics (in-cluster scrape only)
EXPOSE 8011

# The config is mounted, not baked: it carries site coordinates that change
# without a rebuild, and ${...} placeholders resolved from the environment.
CMD ["python", "-m", "weather_exporter", "--config", "/etc/weather-exporter/config.yaml"]
